# Generated by Django 5.2 on 2025-04-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_activities", "0002_module_quizattempt_studentresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Day 1"),
                    (2, "Day 2"),
                    (3, "Day 3"),
                    (4, "Day 4"),
                    (5, "Day 5"),
                ],
                unique=True,
            ),
        ),
    ]
