# Generated by Django 5.2 on 2025-05-14 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom_admin", "0002_alter_student_classroom"),
        ("student_activities", "0003_alter_module_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="inbox_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("pre", "Pre‑Module Quiz"),
                            ("post", "Post‑Module Quiz"),
                        ],
                        max_length=4,
                    ),
                ),
                ("question_text", models.TextField()),
                ("choices", models.JSONField()),
                ("answer", models.CharField(max_length=5)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom_admin.classroom",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
