# Generated by Django 5.2 on 2026-02-17 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_activities', '0004_message_attachment_message_is_read_quizquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read', 'timestamp'], name='student_act_recipie_8d91cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'subject'), name='uniq_sender_recipient_subject'),
        ),
    ]
