# Generated by Codex on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_activities", "0005_message_student_act_recipie_8d91cb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Day 1"),
                    (2, "Day 2"),
                    (3, "Day 3"),
                    (4, "Day 4"),
                    (5, "Day 5"),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("classroom", "day"),
                name="uniq_module_classroom_day",
            ),
        ),
    ]
