# Generated by Django 5.2 on 2025-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbook",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="workbooks/"),
        ),
    ]
