# Generated by Django 5.2 on 2025-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbooks", "0002_workbook_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbook",
            name="import_finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workbook",
            name="import_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
