# Generated by Django 5.2 on 2025-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbooks", "0003_workbook_import_finished_workbook_import_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbook",
            name="import_error",
            field=models.TextField(blank=True),
        ),
    ]
