# Generated by Django 5.2 on 2025-06-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbooks", "0005_remove_workbook_file_question_studentanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="workbook",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="workbooks/pdfs/"),
        ),
    ]
