# Generated by Django 5.2 on 2025-05-14 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom_admin", "0002_alter_student_classroom"),
        (
            "student_activities",
            "0004_message_attachment_message_is_read_quizquestion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"is_teacher": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classroom",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="classroom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="classroom_admin.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ModuleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_assignments",
                        to="classroom_admin.classroom",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_activities.module",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "module")},
            },
        ),
        migrations.CreateModel(
            name="QuizAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("pre", "Pre‑Module Quiz"),
                            ("post", "Post‑Module Quiz"),
                        ],
                        max_length=4,
                    ),
                ),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_assignments",
                        to="classroom_admin.classroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "quiz_type")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="teacher_messages/"
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_messages",
                        to="classroom_admin.classroom",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
