#base.py

"""
Django settings for scitrek_backend project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Here BASE_DIR points to the outer project folder.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "dev-only-scitrek-local-fallback-secret-key-2026-change-for-production-7xQp42",
)

# Custom user model
AUTH_USER_MODEL = 'classroom_admin.CustomUser'

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "classroom_admin.apps.ClassroomsConfig",
    "student_activities.apps.StudentActivitiesConfig",
    "workbooks.apps.WorkbooksConfig",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [value.strip() for value in os.getenv(name, default).split(",") if value.strip()]


def env_int(name, default):
    value = os.getenv(name, str(default))
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f"{name} must be an integer") from exc


def require_env(name):
    value = os.getenv(name)
    if value is None or not value.strip():
        raise ImproperlyConfigured(f"{name} must be set")
    return value


def env_bool_required(name):
    """Like env_bool, but refuses to assume a default.

    For settings where both values are legitimate in different topologies and a
    silently wrong guess is a security regression rather than an inconvenience.
    """
    value = require_env(name).strip().lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a boolean value")


def require_secret_env(name, min_length=50):
    value = require_env(name)
    if len(value) < min_length or "change-me" in value.lower():
        raise ImproperlyConfigured(
            f"{name} must be at least {min_length} characters and must not be an example placeholder"
        )
    return value


CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)
GUEST_LOGIN_ENABLED = env_bool("GUEST_LOGIN_ENABLED", False)
GUEST_CLASSROOM_NAME = os.getenv("GUEST_CLASSROOM_NAME", "1001").strip()
PUBLIC_SIGNUP_ENABLED = env_bool("PUBLIC_SIGNUP_ENABLED", False)

# Content-Security-Policy and Permissions-Policy have no Django setting of their
# own. These values are the same policies the nginx edge applies, kept here so a
# platform without an edge proxy can emit them from the application instead via
# SecurityHeadersMiddleware. Changing one source without the other would make
# the two deployment topologies disagree.
# Platform health checks (Render's, for example) reach the container directly
# over HTTP without a forwarded-proto header, and SECURE_SSL_REDIRECT would
# answer 301, which fails the check. These four endpoints return only a
# liveness/readiness status, so exempting them from the redirect leaks nothing.
# Inert unless SECURE_SSL_REDIRECT is enabled, which only production does.
SECURE_REDIRECT_EXEMPT = [
    r'^healthz/$',
    r'^readyz/$',
    r'^api/health/$',
    r'^api/ready/$',
]

CONTENT_SECURITY_POLICY = os.getenv(
    "CONTENT_SECURITY_POLICY",
    "default-src 'self'; base-uri 'self'; connect-src 'self'; font-src 'self' data:; "
    "frame-ancestors 'none'; frame-src https:; img-src 'self' data: https:; "
    "media-src 'self'; object-src 'none'; script-src 'self'; "
    "style-src 'self' 'unsafe-inline'; upgrade-insecure-requests",
)
PERMISSIONS_POLICY = os.getenv(
    "PERMISSIONS_POLICY",
    "camera=(), microphone=(), geolocation=(), payment=()",
)


# Update these references to reflect the new project module name.
ROOT_URLCONF = "scitrek_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user':     '1000/day',
        'anon':     '100/day',
        'response': '30/minute',   # scoped to ResponseUpsert
        'quiz':     '20/minute',   # scoped to QuizAttemptUpsert
        'token_obtain': '10/minute',
        'token_refresh': '30/minute',
        'signup': '5/hour',
        'guest_login': '10/hour',
    },

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}



WSGI_APPLICATION = "scitrek_backend.wsgi.application"

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", "http://localhost:3000")

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

# STATICFILES_DIRS for additional static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# STATIC_ROOT where static files are collected for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Where uploaded media lives. "filesystem" keeps the shared private volume the
# Compose topology uses. "s3" is required on any platform where web and worker
# run on separate hosts and cannot share a volume: the worker opens the workbook
# PDF the web service saved, so a per-host filesystem would break every import.
# Any S3-compatible provider works; only the endpoint and credentials differ.
MEDIA_STORAGE_BACKEND = os.getenv("MEDIA_STORAGE_BACKEND", "filesystem").strip().lower()

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    },
}

if MEDIA_STORAGE_BACKEND == "s3":
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": require_env("MEDIA_S3_BUCKET"),
            "access_key": require_env("MEDIA_S3_ACCESS_KEY_ID"),
            "secret_key": require_env("MEDIA_S3_SECRET_ACCESS_KEY"),
            # Cloudflare R2, Backblaze B2, and MinIO each need their own
            # endpoint. Empty means real AWS S3, which infers it from the region.
            "endpoint_url": os.getenv("MEDIA_S3_ENDPOINT_URL", "").strip() or None,
            "region_name": os.getenv("MEDIA_S3_REGION", "auto").strip(),
            # MinIO and some providers only serve path-style requests.
            "addressing_style": os.getenv(
                "MEDIA_S3_ADDRESSING_STYLE", "virtual"
            ).strip(),
            "signature_version": "s3v4",
            # Student uploads must never be world-readable. No ACL is sent at
            # all, so objects inherit the bucket's own private default rather
            # than this code silently granting public-read.
            "default_acl": None,
            "querystring_auth": True,
            "querystring_expire": env_int("MEDIA_S3_URL_EXPIRE_SECONDS", 300),
            # Uploads keep Django's suffixed name instead of silently replacing
            # another student's file that happens to share a name.
            "file_overwrite": False,
        },
    }
elif MEDIA_STORAGE_BACKEND != "filesystem":
    raise ImproperlyConfigured(
        'MEDIA_STORAGE_BACKEND must be either "filesystem" or "s3"'
    )

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Broker & result backend (e.g. Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SOFT_TIME_LIMIT = 270
CELERY_TASK_TIME_LIMIT = 300

# Run tasks inline in the calling process instead of handing them to a worker.
# For platforms with no worker process at all: the free tier of a host that
# charges for background workers. Correct for every task here except a
# ScheduledMessage, because eager execution ignores an eta and would send a
# message the moment a teacher saved it. SCHEDULED_MESSAGE_SWEEP covers that.
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', False)

# Who delivers a ScheduledMessage. False: the API enqueues it with an eta and a
# Celery worker holds it until then. True: the API enqueues nothing, the row's
# scheduled_time is the whole schedule, and `manage.py send_due_messages`
# delivers what has come due. The two must not both run, or a message sends
# twice -- though schedule_message_task is idempotent, so it would be harmless.
SCHEDULED_MESSAGE_SWEEP = env_bool('SCHEDULED_MESSAGE_SWEEP', False)

# Shared secret for the endpoint that triggers the sweep from an external
# scheduler. Empty disables the endpoint outright rather than leaving it open.
TASK_RUNNER_TOKEN = os.getenv('TASK_RUNNER_TOKEN', '').strip()

# Optional Celery settings:
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
